tasks:
  - name: bit setup
    init: |
      npx --yes @teambit/bvm install
      echo "export PATH=$HOME/bin:$PATH" >> ~/.bashrc
      echo "export PATH="$PATH:$HOME/.rvm/bin" >> ~/.bashrc
      ## install workspace dependencies
      bit install
      ## Import components from their remote scopes to the local workspace
      bit import
      gp sync-done bundle
    command: bit start
    openMode: split-right

  - name: bit watch
    init: gp sync-await bundle # wait for the above 'init' to finish
    command: bit watch
    openMode: split-right

  - name: start services
    command: docker-compose up
    openMode: split-right

